<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tokens extends Model
{
    use HasFactory;

    protected $fillable =[
        'name','amount', 'active','price'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function user()
    {
        return $this->hasOne(User::class,'id','user_id');
    }
    public function generateCode()
    {
        return rand(10000,999999);
    }
}
